# Generated by Django 5.1.1 on 2024-10-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_alter_ads_id_alter_car_id_alter_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_city',
            field=models.CharField(choices=[('Agadir', 'Agadir'), ('Agadir-Ida Ou Tanane', 'Agadir-Ida Ou Tanane'), ('Al Hoceima', 'Al Hoceima'), ('Ait Melloul', 'Ait Melloul'), ('Azrou', 'Azrou'), ('Bab Taza', 'Bab Taza'), ('Beni Mellal', 'Beni Mellal'), ('Boujad', 'Boujad'), ('Casablanca', 'Casablanca'), ('Chefchaouen', 'Chefchaouen'), ('El Jadida', 'El Jadida'), ('Essaouira', 'Essaouira'), ('Fès', 'Fès'), ('Ifrane', 'Ifrane'), ('Kenitra', 'Kenitra'), ('Khouribga', 'Khouribga'), ('Laâyoune', 'Laâyoune'), ('Larache', 'Larache'), ('Marrakech', 'Marrakech'), ('Meknès', 'Meknès'), ('Mohammedia', 'Mohammedia'), ('Nador', 'Nador'), ('Oujda', 'Oujda'), ('Rabat', 'Rabat'), ('Safi', 'Safi'), ('Sale', 'Sale'), ('Settat', 'Settat'), ('Tanger', 'Tanger'), ('Tétouan', 'Tétouan'), ('Taza', 'Taza'), ('Taroudannt', 'Taroudannt'), ('Ouarzazate', 'Ouarzazate'), ('Tiflet', 'Tiflet'), ('Titouan', 'Titouan'), ('Khemisset', 'Khemisset'), ('Youssoufia', 'Youssoufia'), ('Zagora', 'Zagora'), ('Ouarzazate', 'Ouarzazate'), ('Tiflet', 'Tiflet'), ('Titouan', 'Titouan'), ('Khemisset', 'Khemisset'), ('Youssoufia', 'Youssoufia'), ('Zagora', 'Zagora'), ('Other', 'Other')], default='Patna', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_owner',
            field=models.CharField(choices=[('first owner', 'First Owner'), ('second owner', 'Second Owner'), ('third owner', 'Third Owner'), ('fourth owner or more', 'Fourth Owner or More'), ('new', 'new')], default='first owner', max_length=25),
        ),
    ]
